BEGIN;

CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  author INTEGER NOT NULL REFERENCES user(id),
  created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE body (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE comment (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE style (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE script (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE link (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE user (
  id SERIAL PRIMARY KEY,
  created TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);
CREATE TABLE tag (
  id SERIAL PRIMARY KEY,
  post INTEGER NOT NULL REFERENCES post(id),
  label TEXT NOT NULL
);
CREATE TABLE settings (
  id SERIAL PRIMARY KEY,
);

COMMIT;
