BEGIN;

CREATE TABLE post (
  id SERIAL PRIMARY KEY,
  author INTEGER NOT NULL REFERENCES user(id)
);
CREATE TABLE body (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE comment (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE style (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE script (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE link (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE user (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE tag (
  id SERIAL PRIMARY KEY,
);
CREATE TABLE settings (
  id SERIAL PRIMARY KEY,
);

COMMIT;
